// PepperInjectShell.js - Shell Connection, Message Rendering, Interactive Content
// Module for PepperInject - registers on window.PepperInjectModules.Shell

(function() {
    console.log("PepperInjectShell.js loading...");

    // Track version for change detection
    const MODULE_VERSION = Date.now();
    const prevVersion = window.PepperInjectModules?.Shell?._version;

    // ============================================
    // MESSAGE RULES - Edit this to modify message processing
    // ============================================
    const MESSAGE_RULES = {
        // Suppression rules - messages matching these are completely hidden
        suppress: [
            { id: 'caveat-warning', pattern: /^Caveat: The messages below were generated by the user/ },
            { id: 'system-reminder', pattern: /<system-reminder>[\s\S]*?<\/system-reminder>/ }
        ],
        // Format rules - messages matching these are transformed for display
        format: [
            {
                id: 'command-block',
                pattern: /<command-name>(.*?)<\/command-name>/,
                transform: (match) => ({ type: 'command', name: match[1] })
            }
        ]
    };

    window.PepperInjectModules = window.PepperInjectModules || {};
    window.PepperInjectModules.Shell = {
        _version: MODULE_VERSION,

        // AskUserQuestion state for sequential question flow
        askQuestionState: null,  // { questions, currentIndex, answers, timestamp, containerEl }

        // ============================================
        // INPUT REF LISTENER
        // ============================================

        setupInputRefListener() {
            const inputRefPath = this.V("inputRef");
            if (!inputRefPath) {
                console.log("PepperInject: No inputRef defined");
                return;
            }

            this.inputRefRef = net.db.ref(inputRefPath);
            let isFirstValue = true;

            this.inputRefRef.on("value", (snapshot) => {
                const value = snapshot.val();
                const label = document.getElementById('pepperinject-inputref-label');

                if (isFirstValue) {
                    isFirstValue = false;
                    if (label) {
                        if (value === null || value === "") {
                            label.value = "";
                            label.style.color = "#666";
                        } else {
                            label.value = value;
                            label.style.color = "#e8e8e8";
                        }
                    }
                    return;
                }

                if (value === null || value === "") {
                    if (label) {
                        label.value = "";
                        label.style.color = "#666";
                    }
                } else {
                    if (label) {
                        label.value = value;
                        label.style.color = "#e8e8e8";
                    }
                    this.flashInputRow();
                    if (this.isConnected && this.stdinRef) {
                        this.sendToShellStdin(value);
                    }
                }
            });
        },

        flashInputRow() {
            const label = document.getElementById('pepperinject-inputref-label');
            if (label) {
                label.style.borderColor = "#00ff00";
                setTimeout(() => {
                    label.style.borderColor = "#3a3a3a";
                }, 300);
            }
        },

        // ============================================
        // SHELL CONNECTION
        // ============================================

        connectShell(sessionName) {
            if (this.isConnected) {
                this.disconnectShell();
            }

            this.currentSession = sessionName;
            console.log("PepperInject: Connecting to shell:", sessionName);

            const sessionLabel = document.getElementById('pepperinject-session-label');
            if (sessionLabel) {
                sessionLabel.textContent = sessionName;
                sessionLabel.style.color = "#e8e8e8";
            }

            this.shellRef = net.db.ref(`/shell/${sessionName}`);
            this.stdinRef = this.shellRef.child('stdin');
            this.metaRef = this.shellRef.child('meta');

            // Get current stdin index
            this.stdinRef.once('value', (snapshot) => {
                const data = snapshot.val();
                if (data && typeof data === 'object') {
                    const keys = Object.keys(data).map(k => parseInt(k));
                    this.stdinIndex = Math.max(...keys, -1) + 1;
                } else {
                    this.stdinIndex = 0;
                }
            });

            // Listen for metadata
            this.metaRef.on('value', (snapshot) => {
                const meta = snapshot.val();
                if (meta) {
                    this.updateShellStatus(meta.status || 'unknown');
                } else {
                    this.updateShellStatus('not_found');
                }
            });

            // Listen for messages
            this.shellRef.on('child_added', (snapshot) => {
                const key = snapshot.key;
                if (key === 'meta' || key === 'stdin') return;

                const data = snapshot.val();
                if (data && data.role) {
                    this.messages.set(key, data);
                    this.renderMessages();
                    this.checkForClearCommand(data);
                }
            });

            this.shellRef.on('child_changed', (snapshot) => {
                const key = snapshot.key;
                if (key === 'meta' || key === 'stdin') return;

                const data = snapshot.val();
                if (data && data.role) {
                    this.messages.set(key, data);
                    this.renderMessages();
                    this.checkForClearCommand(data);
                }
            });

            this.isConnected = true;
            this.updateConnectButton();
        },

        disconnectShell() {
            console.log("PepperInject: Disconnecting shell...");

            if (this.shellRef) {
                this.shellRef.off();
                this.shellRef = null;
            }
            if (this.metaRef) {
                this.metaRef.off();
                this.metaRef = null;
            }
            this.stdinRef = null;
            this.messages.clear();
            this.stdinIndex = 0;
            this.isConnected = false;

            this.updateShellStatus('disconnected');
            this.updateConnectButton();
            this.clearMessagesUI();
            this.showEmptyState();

            const msgCount = document.getElementById('pepperinject-msgcount');
            if (msgCount) msgCount.textContent = "";
        },

        updateShellStatus(status) {
            const dot = document.getElementById('pepperinject-status-dot');
            const text = document.getElementById('pepperinject-status-text');

            const colors = {
                'running': '#00ff00',
                'completed': '#00d4ff',
                'error': '#ff4444',
                'interrupted': '#ffaa00',
                'not_found': '#666',
                'disconnected': '#666'
            };

            const labels = {
                'running': 'Running',
                'completed': 'Completed',
                'error': 'Error',
                'interrupted': 'Interrupted',
                'not_found': 'Not Found',
                'disconnected': 'Disconnected',
                'unknown': 'Unknown'
            };

            if (dot) dot.style.background = colors[status] || '#666';
            if (text) text.textContent = labels[status] || status;
        },

        updateConnectButton() {
            const btn = document.getElementById('pepperinject-connect-btn');
            if (!btn) return;

            if (this.isConnected) {
                btn.textContent = "Disconnect";
                btn.style.background = "rgba(0, 212, 255, 0.15)";
                btn.style.borderColor = "#00d4ff";
                btn.style.color = "#00d4ff";
            } else {
                btn.textContent = "Connect";
                btn.style.background = "#2a2a2a";
                btn.style.borderColor = "#3a3a3a";
                btn.style.color = "#e8e8e8";
            }
        },

        // ============================================
        // SHELL STDIN
        // ============================================

        sendToShellStdin(text) {
            if (!text || !this.stdinRef) return;

            this.stdinRef.child(String(this.stdinIndex)).set(text)
                .then(() => {
                    this.stdinIndex++;
                    console.log("PepperInject: Sent to stdin:", text);
                })
                .catch(err => {
                    console.error("PepperInject: Failed to send stdin:", err);
                });
        },

        sendShellInput() {
            const label = document.getElementById('pepperinject-inputref-label');
            const currentText = label?.value?.trim();
            if (this.isConnected && this.stdinRef && currentText) {
                this.sendToShellStdin(currentText);
                label.style.color = "#444";
            }
        },

        clearShellMessages() {
            if (!this.isConnected || !this.shellRef) return;

            // Get and disable the clear button
            const clearBtn = document.getElementById('pepperinject-shell-clear-btn');
            if (clearBtn) {
                clearBtn.disabled = true;
                clearBtn.style.opacity = '0.5';
                clearBtn.style.cursor = 'not-allowed';
            }

            // Show splash screen
            const container = document.getElementById('pepperinject-messages');
            if (container) {
                container.innerHTML = `
                    <div style="display: flex; flex-direction: column; align-items: center; justify-content: center; padding: 40px; color: #ffc107;">
                        <span style="font-size: 32px; margin-bottom: 12px;">⏳</span>
                        <span style="font-size: 12px;">Please wait restarting shell</span>
                    </div>
                `;
            }

            // Clear the input ref label
            const inputRefLabel = document.getElementById('pepperinject-inputref-label');
            if (inputRefLabel) {
                inputRefLabel.value = "";
                inputRefLabel.style.color = "#666";
            }

            this.sendToShellStdin("/clear");

            setTimeout(() => {
                // Re-enable button helper
                const reEnableButton = () => {
                    if (clearBtn) {
                        clearBtn.disabled = false;
                        clearBtn.style.opacity = '1';
                        clearBtn.style.cursor = 'pointer';
                    }
                };

                // Check connection before proceeding
                if (this.isConnected && this.metaRef) {
                    this.shellRef.once('value', (snapshot) => {
                        const data = snapshot.val();
                        if (data) {
                            const updates = {};
                            for (const key of Object.keys(data)) {
                                if (key !== 'meta' && key !== 'stdin') {
                                    updates[key] = null;
                                }
                            }
                            this.shellRef.update(updates)
                                .then(() => {
                                    console.log("PepperInject: Cleared shell messages");
                                    this.messages.clear();
                                    this.clearMessagesUI();
                                    this.showEmptyState();
                                    const msgCount = document.getElementById('pepperinject-msgcount');
                                    if (msgCount) msgCount.textContent = "";
                                    reEnableButton();
                                })
                                .catch(err => {
                                    console.error("PepperInject: Clear failed:", err);
                                    reEnableButton();
                                });
                        } else {
                            this.showEmptyState();
                            reEnableButton();
                        }
                    });
                } else {
                    // Not connected - just re-enable button and show empty state
                    this.showEmptyState();
                    reEnableButton();
                }
            }, 3000);
        },

        // ============================================
        // SPECIAL CONTENT DETECTION
        // ============================================

        checkForClearCommand(data) {
            // Currently disabled - kept for future use
            // if (data.role !== 'user') return;
            // ...
        },

        // ============================================
        // MESSAGE PROCESSING
        // ============================================

        processMessageContent(content) {
            if (typeof content !== 'string') return content;

            // Check suppression rules first
            for (const rule of MESSAGE_RULES.suppress) {
                if (rule.pattern.test(content)) {
                    return null; // Suppress this content
                }
            }

            // Check format rules
            for (const rule of MESSAGE_RULES.format) {
                const match = content.match(rule.pattern);
                if (match) {
                    return rule.transform(match);
                }
            }

            return content; // No rules matched, return as-is
        },

        renderCommandBlock(data) {
            const block = document.createElement('div');
            block.className = 'pepperinject-command-block';
            block.style.cssText = `
                display: inline-block;
                background: rgba(0, 212, 255, 0.15);
                border: 1px solid #00d4ff;
                border-radius: 4px;
                padding: 2px 8px;
                margin: 2px 0;
            `;

            const nameSpan = document.createElement('span');
            nameSpan.className = 'pepperinject-command-name';
            nameSpan.style.cssText = `
                color: #00d4ff;
                font-family: monospace;
                font-size: 12px;
            `;
            nameSpan.textContent = data.name;
            block.appendChild(nameSpan);

            return block;
        },

        // ============================================
        // MESSAGE RENDERING
        // ============================================

        clearMessagesUI() {
            const container = document.getElementById('pepperinject-messages');
            if (container) {
                container.innerHTML = "";
            }
        },

        showEmptyState() {
            const container = document.getElementById('pepperinject-messages');
            if (container) {
                const message = this.isConnected
                    ? "Connected: Send something to Claude"
                    : "Connect to view Claude shell transcript";
                container.innerHTML = `
                    <div id="pepperinject-empty-state" style="display: flex; flex-direction: column; align-items: center; justify-content: center; padding: 40px; color: #666;">
                        <span style="font-size: 32px; margin-bottom: 12px;">💬</span>
                        <span style="font-size: 12px;">${message}</span>
                    </div>
                `;
            }
        },

        renderMessages() {
            const container = document.getElementById('pepperinject-messages');
            if (!container) return;

            container.innerHTML = "";

            const sortedEntries = [...this.messages.entries()].sort((a, b) => a[0].localeCompare(b[0]));

            for (const [ts, msg] of sortedEntries) {
                const msgEl = this.createMessageElement(msg.role, msg.content);
                if (msgEl) {
                    container.appendChild(msgEl);
                }
            }

            const msgCount = document.getElementById('pepperinject-msgcount');
            if (msgCount) {
                msgCount.textContent = `${this.messages.size} messages`;
            }

            // Auto scroll to bottom
            container.scrollTop = container.scrollHeight;
        },

        createMessageElement(role, content) {
            const wrapper = document.createElement('div');
            wrapper.className = `pepperinject-msg pepperinject-msg-${role}`;

            const header = document.createElement('div');
            header.className = 'pepperinject-msg-header';
            header.textContent = role.toUpperCase();
            wrapper.appendChild(header);

            const bubble = document.createElement('div');
            bubble.className = 'pepperinject-msg-bubble';

            if (Array.isArray(content)) {
                for (const item of content) {
                    const el = this.renderContentItem(item);
                    bubble.appendChild(el);
                }
            } else if (typeof content === 'string') {
                const processed = this.processMessageContent(content);
                if (processed === null) {
                    // Entire message suppressed
                } else if (typeof processed === 'object' && processed.type === 'command') {
                    bubble.appendChild(this.renderCommandBlock(processed));
                } else {
                    bubble.textContent = processed;
                }
            }

            // Check if bubble has any visible content
            const hasVisibleContent = bubble.textContent.trim() !== '' ||
                [...bubble.children].some(child => child.style.display !== 'none');

            if (!hasVisibleContent) {
                return null; // Don't render empty messages
            }

            wrapper.appendChild(bubble);
            return wrapper;
        },

        renderContentItem(item) {
            // Process string content through message rules
            if (typeof item === 'string') {
                const processed = this.processMessageContent(item);

                // Suppressed content - return hidden element
                if (processed === null) {
                    const span = document.createElement('span');
                    span.style.display = 'none';
                    return span;
                }

                // Formatted content - handle by type
                if (typeof processed === 'object' && processed.type === 'command') {
                    return this.renderCommandBlock(processed);
                }

                // Normal string content
                const span = document.createElement('span');
                span.textContent = processed;
                return span;
            }

            if (typeof item === 'object' && item !== null) {
                // Process text content through message rules
                if (item.type === 'text' || item.text) {
                    const textContent = item.text || '';
                    const processed = this.processMessageContent(textContent);

                    // Suppressed content
                    if (processed === null) {
                        const span = document.createElement('span');
                        span.style.display = 'none';
                        return span;
                    }

                    // Formatted content
                    if (typeof processed === 'object' && processed.type === 'command') {
                        return this.renderCommandBlock(processed);
                    }

                    // Normal text
                    const span = document.createElement('span');
                    span.textContent = processed;
                    return span;
                }

                if (item.type === 'tool_use') {
                    // Special handling for AskUserQuestion - render as clickable buttons
                    if (item.name === 'AskUserQuestion' && item.input?.questions) {
                        return this.renderAskUserQuestion(item.input.questions);
                    }
                    // Special handling for Edit - render as confirmation with diff
                    if (item.name === 'Edit' && item.input?.file_path) {
                        return this.renderEditConfirmation(item.input);
                    }
                    return this.renderToolBlock('tool_use', item.name, item.input);
                }

                if (item.type === 'tool_result') {
                    return this.renderToolBlock('tool_result', 'Result', item.content);
                }

                if (item.type === 'thinking' || item.thinking) {
                    return this.renderThinkingBlock(item.thinking || item.text || '');
                }

                const span = document.createElement('span');
                span.textContent = JSON.stringify(item, null, 2);
                span.style.color = "#888";
                span.style.fontSize = "10px";
                return span;
            }

            const span = document.createElement('span');
            span.textContent = String(item);
            return span;
        },

        renderToolBlock(type, name, data) {
            const block = document.createElement('div');
            block.className = `pepperinject-tool-block ${type === 'tool_result' ? 'result' : ''}`;

            const nameEl = document.createElement('div');
            nameEl.className = 'pepperinject-tool-name';
            nameEl.style.color = type === 'tool_result' ? '#00ff00' : '#ffaa00';
            nameEl.textContent = name;
            block.appendChild(nameEl);

            const contentEl = document.createElement('div');
            contentEl.className = 'pepperinject-tool-content';
            contentEl.textContent = typeof data === 'string' ? data : JSON.stringify(data, null, 2);
            block.appendChild(contentEl);

            return block;
        },

        renderThinkingBlock(content) {
            const block = document.createElement('div');
            block.className = 'pepperinject-thinking-block';
            block.textContent = content;
            return block;
        },

        // ============================================
        // INTERACTIVE CONTENT
        // ============================================

        renderAskUserQuestion(questions) {
            const timestamp = Date.now();
            const container = document.createElement('div');
            container.className = 'pepperinject-ask-container';
            container.id = `pepperinject-ask-${timestamp}`;

            // Initialize state for sequential question flow
            this.askQuestionState = {
                questions: questions,
                currentIndex: 0,
                answers: [],
                timestamp: timestamp,
                containerEl: container
            };

            // Render the first question
            this.renderCurrentQuestion();

            return container;
        },

        renderCurrentQuestion() {
            const state = this.askQuestionState;
            if (!state) return;

            const { questions, currentIndex, containerEl } = state;

            // If all questions answered, submit
            if (currentIndex >= questions.length) {
                this.submitAllAnswers();
                return;
            }

            const q = questions[currentIndex];
            containerEl.innerHTML = '';  // Clear previous content

            // Question div
            const questionDiv = document.createElement('div');
            questionDiv.className = 'pepperinject-question';

            // Question header with progress indicator
            const header = document.createElement('div');
            header.className = 'pepperinject-question-header';
            const progress = questions.length > 1 ? ` (${currentIndex + 1}/${questions.length})` : '';
            header.innerHTML = `<span class="pepperinject-question-tag">${q.header || 'Question'}${progress}</span> ${q.question}`;
            questionDiv.appendChild(header);

            // Options as vertical list
            const optionsDiv = document.createElement('div');
            optionsDiv.className = 'pepperinject-options';

            q.options.forEach((opt, idx) => {
                const optionNumber = idx + 1;
                const btn = document.createElement('button');
                btn.className = 'pepperinject-option-btn';
                btn.innerHTML = `
                    <span class="pepperinject-option-num">${optionNumber}</span>
                    <span class="pepperinject-option-label">${opt.label}</span>
                    ${opt.description ? `<span class="pepperinject-option-desc">- ${opt.description}</span>` : ''}
                `;
                btn.addEventListener('click', () => this.selectOption(optionNumber));
                optionsDiv.appendChild(btn);
            });

            // Add "Other" custom input as the last option
            const otherOptionNumber = q.options.length + 1;
            const inputRow = document.createElement('div');
            inputRow.className = 'pepperinject-ask-input-row';
            inputRow.innerHTML = `
                <span class="pepperinject-option-num">${otherOptionNumber}</span>
                <input type="text" class="pepperinject-ask-input" placeholder="Other...">
                <button class="pepperinject-ask-send">Send</button>
            `;

            const inputField = inputRow.querySelector('.pepperinject-ask-input');
            const sendBtn = inputRow.querySelector('.pepperinject-ask-send');

            const sendCustom = () => {
                const text = inputField.value.trim();
                if (text) {
                    this.selectOption(text);  // Pass custom text
                }
            };

            sendBtn.addEventListener('click', sendCustom);
            inputField.addEventListener('keypress', (e) => {
                if (e.key === 'Enter') {
                    e.preventDefault();
                    sendCustom();
                }
            });

            optionsDiv.appendChild(inputRow);
            questionDiv.appendChild(optionsDiv);
            containerEl.appendChild(questionDiv);
        },

        selectOption(value) {
            const state = this.askQuestionState;
            if (!state) return;

            // Store the answer
            state.answers.push(value);
            state.currentIndex++;

            console.log(`PepperInject: Selected option ${value}, answers so far:`, state.answers);

            // Render next question or submit all
            this.renderCurrentQuestion();
        },

        submitAllAnswers() {
            const state = this.askQuestionState;
            if (!state) return;

            const { answers, containerEl } = state;

            // Show sending message
            containerEl.innerHTML = `
                <div style="color: #90EE90; padding: 8px; text-align: center; font-size: 12px;">
                    Sending ${answers.length} answer(s)...
                </div>
            `;

            // Send answers sequentially with delays
            // All but last use :noenter, last one triggers the Enter
            answers.forEach((answer, idx) => {
                const isLast = idx === answers.length - 1;
                const delay = idx * 150;  // 150ms between each

                setTimeout(() => {
                    const ts = Date.now();
                    const suffix = isLast ? '' : ':noenter';
                    const value = `${ts}:${answer}${suffix}`;
                    this.sendToShellStdin(value);

                    console.log(`PepperInject: Sent answer ${idx + 1}/${answers.length}: ${value}`);

                    if (isLast) {
                        // Update UI to show completion
                        containerEl.innerHTML = `
                            <div style="color: #90EE90; padding: 8px; text-align: center; font-size: 12px;">
                                Answers submitted
                            </div>
                        `;
                        this.askQuestionState = null;
                    }
                }, delay);
            });
        },

        sendOptionToStdin(optionIndex) {
            // Legacy method - kept for compatibility with other uses
            // Use timestamp:index format to ensure uniqueness
            const timestamp = Date.now();
            const value = `${timestamp}:${optionIndex}`;
            this.sendToShellStdin(value);

            console.log(`PepperInject: Sent option index ${optionIndex} as ${value}`);
        },

        renderEditConfirmation(input) {
            const container = document.createElement('div');
            container.className = 'pepperinject-edit-container';

            // Extract filename from path
            const filePath = input.file_path || '';
            const fileName = filePath.split('/').pop() || 'unknown';

            // Header
            const header = document.createElement('div');
            header.className = 'pepperinject-edit-header';
            header.innerHTML = `
                <span class="pepperinject-edit-icon">✏️</span>
                <span class="pepperinject-edit-title">Edit Confirmation</span>
                <span class="pepperinject-edit-file">${fileName}</span>
            `;
            container.appendChild(header);

            // Diff preview
            const diffDiv = document.createElement('div');
            diffDiv.className = 'pepperinject-edit-diff';

            const oldString = input.old_string || '';
            const newString = input.new_string || '';

            // Show truncated diff
            const maxLines = 8;
            const oldLines = oldString.split('\n').slice(0, maxLines);
            const newLines = newString.split('\n').slice(0, maxLines);

            let diffHtml = '';
            oldLines.forEach(line => {
                const escapedLine = this.escapeHtml(line);
                diffHtml += `<span class="pepperinject-diff-old">- ${escapedLine}</span>`;
            });
            if (oldString.split('\n').length > maxLines) {
                diffHtml += `<span class="pepperinject-diff-old">... (${oldString.split('\n').length - maxLines} more lines)</span>`;
            }
            newLines.forEach(line => {
                const escapedLine = this.escapeHtml(line);
                diffHtml += `<span class="pepperinject-diff-new">+ ${escapedLine}</span>`;
            });
            if (newString.split('\n').length > maxLines) {
                diffHtml += `<span class="pepperinject-diff-new">... (${newString.split('\n').length - maxLines} more lines)</span>`;
            }

            diffDiv.innerHTML = diffHtml;
            container.appendChild(diffDiv);

            // Options
            const optionsDiv = document.createElement('div');
            optionsDiv.className = 'pepperinject-edit-options';

            // Option 1: Yes
            const btn1 = document.createElement('button');
            btn1.className = 'pepperinject-edit-btn';
            btn1.innerHTML = `
                <span class="pepperinject-edit-btn-num">1</span>
                <span class="pepperinject-edit-btn-text">Yes</span>
            `;
            btn1.addEventListener('click', () => this.sendOptionToStdin(1));
            optionsDiv.appendChild(btn1);

            // Option 2: Yes, allow all edits
            const btn2 = document.createElement('button');
            btn2.className = 'pepperinject-edit-btn';
            btn2.innerHTML = `
                <span class="pepperinject-edit-btn-num">2</span>
                <span class="pepperinject-edit-btn-text">Yes, allow all edits during this session</span>
            `;
            btn2.addEventListener('click', () => this.sendOptionToStdin(2));
            optionsDiv.appendChild(btn2);

            // Option 3: Custom input
            const inputRow = document.createElement('div');
            inputRow.className = 'pepperinject-edit-input-row';
            inputRow.innerHTML = `
                <span class="pepperinject-edit-btn-num">3</span>
                <input type="text" class="pepperinject-edit-input" placeholder="Tell Claude what to do differently...">
                <button class="pepperinject-edit-input-send">Send</button>
            `;

            const inputField = inputRow.querySelector('.pepperinject-edit-input');
            const sendBtn = inputRow.querySelector('.pepperinject-edit-input-send');

            const sendCustomInput = () => {
                const text = inputField.value.trim();
                if (text) {
                    this.sendCustomTextToStdin(text);
                    inputField.value = '';
                }
            };

            sendBtn.addEventListener('click', sendCustomInput);
            inputField.addEventListener('keypress', (e) => {
                if (e.key === 'Enter') {
                    sendCustomInput();
                }
            });

            optionsDiv.appendChild(inputRow);
            container.appendChild(optionsDiv);

            return container;
        },

        sendCustomTextToStdin(text) {
            // Use timestamp:text format for custom input
            const timestamp = Date.now();
            const value = `${timestamp}:${text}`;
            this.sendToShellStdin(value);
            console.log(`PepperInject: Sent custom text as ${value}`);
        },

        // ============================================
        // UTILITY
        // ============================================

        escapeHtml(text) {
            const div = document.createElement('div');
            div.textContent = text;
            return div.innerHTML;
        }
    };

    // REFRESH TRIGGER: If main instance exists and module was updated, trigger refresh
    if (prevVersion && prevVersion !== MODULE_VERSION) {
        console.log("PepperInjectShell.js: Module updated, triggering refresh...");
        if (window.pepperInjectInstance?._component) {
            window.pepperInjectInstance._component._refresh();
        }
    }

    console.log("PepperInjectShell.js: Module registered (v" + MODULE_VERSION + ")");
})();
